### ISSUE TITLE
Sample design?

### ISSUE THREAD

**Issue by ghost** [iamNCJ/PYNQ-CDMA-Driver#1]
Can you provide a simple block design that I can use the library?

**Comment by iamNCJ** [comment]
Hi, here is a prototype block design I used when developing this driver,
![image](https://user-images.githubusercontent.com/28685287/214831827-4ba4ae5c-5b89-4568-a05b-d1225d5fe5de.png)
and the corresponding address map:
![image](https://user-images.githubusercontent.com/28685287/214831893-f06af32e-53d3-4fa5-a5c8-c9524b21592e.png)
Hope this can help you.

**Comment by ghost** [comment]
Thank you. Are you using Kria SOM?

**Comment by iamNCJ** [comment]
> Thank you. Are you using Kria SOM?

No, I was using a development board from ALINX when developing this driver. IMO the highlight of Kria is more of IO extension with some software integration, which can save a lot of time and effort rather than putting all these software and hardware together by hand during prototyping. However, the core of Kria is still an UltraScale+ Zynq, hence the driver can still be used since the old zynq/pynq development workflows can still work.

**Comment by ghost** [comment]
What is `TestBoardChisel_0`? Is it a custom block? Should I have that to use the driver?

**Comment by iamNCJ** [comment]
> What is `TestBoardChisel_0`? Is it a custom block? Should I have that to use the driver?

Yes, it's a custom overlay and you can ignore that.
